#!/usr/bin/perl

use FindBin;
use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../extlib/lib/perl5";
use local::lib "$FindBin::Bin/../extlib";

use Getopt::Long;
use Tamale::Tracker;

my %opt;

GetOptions (
  "username=s" => \$opt{username},
  "password=s" => \$opt{password},
);

if (!$opt{username} or !$opt{password}) {
  die "need username and password options\n";
}

my $tracker = Tamale::Tracker->new(
  datadir  => "$FindBin::Bin/../data",
  username => $opt{username},
  password => $opt{password},
);

$tracker->get_missing_tweets;
