#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use JSON;
use Tamale::Tracker;

binmode(STDOUT, ":utf8");

my $tracker = Tamale::Tracker->new(datadir => "$FindBin::Bin/../data");
my $matches = $tracker->matching_tweets;
print to_json $matches, {pretty => 1};
